meta:
  site_title: "Planit"
  site_subtitle: "Events by Colin"
  site_language: "en"
  absolute_baseurl: 
  domain: 
  author:
    full_name: Colin Vatcher
    short_name: cvatch
    email:fairyqueen6615@gmail.com

pygments: true
markdown: rdiscount
permalink: pretty
